export type LandingDef = {
  slug: string;
  title: string;
  city?: string;
  category?: string;
  variant?: string;
  metaDescription: string;
  ogImage: string;
};

export const SEO_LANDING_PAGES: LandingDef[] = [
  { slug:"best-med-spas-dallas", title:"Best Med Spas in Dallas (2025 Ranked)", city:"Dallas", category:"Med Spa", variant:"ranked", metaDescription:"Best Med Spas in Dallas (2025 Ranked). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-med-spas-dallas.png" },
  { slug:"best-med-spas-plano", title:"Best Med Spas in Plano (Top 10)", city:"Plano", category:"Med Spa", metaDescription:"Best Med Spas in Plano (Top 10). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-med-spas-plano.png" },
  { slug:"best-med-spas-frisco", title:"Best Med Spas in Frisco (Expert Picks)", city:"Frisco", category:"Med Spa", metaDescription:"Best Med Spas in Frisco (Expert Picks). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-med-spas-frisco.png" },
  { slug:"best-med-spas-fort-worth", title:"Best Med Spas in Fort Worth (Top Rated)", city:"Fort Worth", category:"Med Spa", metaDescription:"Best Med Spas in Fort Worth (Top Rated). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-med-spas-fort-worth.png" },
  { slug:"best-med-spas-arlington", title:"Best Med Spas in Arlington (Where Locals Go)", city:"Arlington", category:"Med Spa", metaDescription:"Best Med Spas in Arlington (Where Locals Go). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-med-spas-arlington.png" },
  { slug:"best-med-spas-irving", title:"Best Med Spas in Irving (Top Treatments)", city:"Irving", category:"Med Spa", metaDescription:"Best Med Spas in Irving (Top Treatments). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-med-spas-irving.png" },
  { slug:"best-med-spas-mckinney", title:"Best Med Spas in McKinney (Customer Favorites)", city:"McKinney", category:"Med Spa", metaDescription:"Best Med Spas in McKinney (Customer Favorites). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-med-spas-mckinney.png" },
  { slug:"best-med-spas-allen", title:"Best Med Spas in Allen (Most Reviewed)", city:"Allen", category:"Med Spa", metaDescription:"Best Med Spas in Allen (Most Reviewed). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-med-spas-allen.png" },

  { slug:"best-botox-clinics-dallas", title:"Best Botox Clinics in Dallas (Top Providers)", city:"Dallas", category:"Botox", metaDescription:"Best Botox Clinics in Dallas (Top Providers). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-botox-clinics-dallas.png" },
  { slug:"best-botox-clinics-plano", title:"Best Botox Clinics in Plano (Verified Reviews)", city:"Plano", category:"Botox", metaDescription:"Best Botox Clinics in Plano (Verified Reviews). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-botox-clinics-plano.png" },
  { slug:"best-botox-clinics-frisco", title:"Best Botox Clinics in Frisco (Where to Get Botox Safely)", city:"Frisco", category:"Botox", metaDescription:"Best Botox Clinics in Frisco (Where to Get Botox Safely). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-botox-clinics-frisco.png" },
  { slug:"best-botox-clinics-fort-worth", title:"Best Botox Clinics in Fort Worth (Top Aesthetic Injectors)", city:"Fort Worth", category:"Botox", metaDescription:"Best Botox Clinics in Fort Worth (Top Aesthetic Injectors). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-botox-clinics-fort-worth.png" },
  { slug:"best-lip-filler-specialists-dallas", title:"Best Lip Filler Specialists in Dallas (Beautiful Natural Results)", city:"Dallas", category:"Lip Filler", metaDescription:"Best Lip Filler Specialists in Dallas (Beautiful Natural Results). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-lip-filler-specialists-dallas.png" },
  { slug:"best-lip-filler-specialists-plano", title:"Best Lip Filler Specialists in Plano (Expert Injectors)", city:"Plano", category:"Lip Filler", metaDescription:"Best Lip Filler Specialists in Plano (Expert Injectors). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-lip-filler-specialists-plano.png" },
  { slug:"best-lip-filler-specialists-frisco", title:"Best Lip Filler Specialists in Frisco (Top Ratings)", city:"Frisco", category:"Lip Filler", metaDescription:"Best Lip Filler Specialists in Frisco (Top Ratings). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-lip-filler-specialists-frisco.png" },

  { slug:"best-lash-extensions-dallas", title:"Best Lash Extensions in Dallas (Volume + Hybrid)", city:"Dallas", category:"Lashes", metaDescription:"Best Lash Extensions in Dallas (Volume + Hybrid). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-lash-extensions-dallas.png" },
  { slug:"best-lash-extensions-plano", title:"Best Lash Extensions in Plano (Top Lash Techs)", city:"Plano", category:"Lashes", metaDescription:"Best Lash Extensions in Plano (Top Lash Techs). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-lash-extensions-plano.png" },
  { slug:"best-lash-extensions-frisco", title:"Best Lash Extensions in Frisco (Where to Get Stunning Lashes)", city:"Frisco", category:"Lashes", metaDescription:"Best Lash Extensions in Frisco (Where to Get Stunning Lashes). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-lash-extensions-frisco.png" },
  { slug:"best-lash-extensions-arlington", title:"Best Lash Extensions in Arlington (Affordable + Skilled)", city:"Arlington", category:"Lashes", metaDescription:"Best Lash Extensions in Arlington (Affordable + Skilled). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-lash-extensions-arlington.png" },
  { slug:"best-lash-lifts-dallas", title:"Best Lash Lifts in Dallas (Natural Look Experts)", city:"Dallas", category:"Lashes", metaDescription:"Best Lash Lifts in Dallas (Natural Look Experts). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-lash-lifts-dallas.png" },

  { slug:"best-facial-treatments-dallas", title:"Best Facial Treatments in Dallas (Hydrafacial, Peels & More)", city:"Dallas", category:"Facials", metaDescription:"Best Facial Treatments in Dallas (Hydrafacial, Peels & More). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-facial-treatments-dallas.png" },
  { slug:"best-facial-treatments-plano", title:"Best Facial Treatments in Plano (Top Estheticians)", city:"Plano", category:"Facials", metaDescription:"Best Facial Treatments in Plano (Top Estheticians). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-facial-treatments-plano.png" },
  { slug:"best-facial-treatments-frisco", title:"Best Facial Treatments in Frisco (Glowing Skin Guaranteed)", city:"Frisco", category:"Facials", metaDescription:"Best Facial Treatments in Frisco (Glowing Skin Guaranteed). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-facial-treatments-frisco.png" },
  { slug:"best-microneedling-dallas", title:"Best Microneedling Clinics in Dallas (Skin Rejuvenation)", city:"Dallas", category:"Microneedling", metaDescription:"Best Microneedling Clinics in Dallas (Skin Rejuvenation). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-microneedling-dallas.png" },
  { slug:"best-chemical-peels-dallas", title:"Best Chemical Peel Clinics in Dallas (For All Skin Types)", city:"Dallas", category:"Chemical Peels", metaDescription:"Best Chemical Peel Clinics in Dallas (For All Skin Types). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-chemical-peels-dallas.png" },
  { slug:"best-acne-facials-dallas", title:"Best Acne Facial Clinics in Dallas (Teen + Adult Treatments)", city:"Dallas", category:"Facials", metaDescription:"Best Acne Facial Clinics in Dallas (Teen + Adult Treatments). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-acne-facials-dallas.png" },

  { slug:"best-laser-hair-removal-dallas", title:"Best Laser Hair Removal in Dallas (Safe & Effective)", city:"Dallas", category:"Laser Hair Removal", metaDescription:"Best Laser Hair Removal in Dallas (Safe & Effective). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-laser-hair-removal-dallas.png" },
  { slug:"best-laser-hair-removal-plano", title:"Best Laser Hair Removal in Plano (Top Technology)", city:"Plano", category:"Laser Hair Removal", metaDescription:"Best Laser Hair Removal in Plano (Top Technology). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-laser-hair-removal-plano.png" },
  { slug:"best-laser-hair-removal-frisco", title:"Best Laser Hair Removal in Frisco (Long-Lasting Results)", city:"Frisco", category:"Laser Hair Removal", metaDescription:"Best Laser Hair Removal in Frisco (Long-Lasting Results). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-laser-hair-removal-frisco.png" },
  { slug:"best-brazilian-laser-dallas", title:"Best Brazilian Laser Hair Removal in Dallas (Comfort-Focused)", city:"Dallas", category:"Laser Hair Removal", metaDescription:"Best Brazilian Laser Hair Removal in Dallas (Comfort-Focused). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-brazilian-laser-dallas.png" },

  { slug:"best-nail-salons-dallas", title:"Best Nail Salons in Dallas (Top Trends)", city:"Dallas", category:"Nails", metaDescription:"Best Nail Salons in Dallas (Top Trends). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-nail-salons-dallas.png" },
  { slug:"best-nail-salons-plano", title:"Best Nail Salons in Plano (Gel, Dip & Acrylic)", city:"Plano", category:"Nails", metaDescription:"Best Nail Salons in Plano (Gel, Dip & Acrylic). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-nail-salons-plano.png" },
  { slug:"best-nail-salons-frisco", title:"Best Nail Salons in Frisco (Skill + Style)", city:"Frisco", category:"Nails", metaDescription:"Best Nail Salons in Frisco (Skill + Style). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-nail-salons-frisco.png" },
  { slug:"best-mani-pedi-dallas", title:"Best Mani-Pedi Spots in Dallas (Relax + Refresh)", city:"Dallas", category:"Nails", metaDescription:"Best Mani-Pedi Spots in Dallas (Relax + Refresh). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-mani-pedi-dallas.png" },
  { slug:"best-brow-lamination-dallas", title:"Best Brow Lamination in Dallas (Perfect Brows)", city:"Dallas", category:"Brows", metaDescription:"Best Brow Lamination in Dallas (Perfect Brows). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-brow-lamination-dallas.png" },
  { slug:"best-brow-threading-dallas", title:"Best Brow Threading in Dallas (Precision Artists)", city:"Dallas", category:"Brows", metaDescription:"Best Brow Threading in Dallas (Precision Artists). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-brow-threading-dallas.png" },

  { slug:"best-teeth-whitening-dallas", title:"Best Teeth Whitening Services in Dallas (Instant Brightening)", city:"Dallas", category:"Teeth Whitening", metaDescription:"Best Teeth Whitening Services in Dallas (Instant Brightening). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-teeth-whitening-dallas.png" },
  { slug:"best-cosmetic-dentists-dallas", title:"Best Cosmetic Dentists in Dallas (Smile Makeovers)", city:"Dallas", category:"Cosmetic Dentistry", metaDescription:"Best Cosmetic Dentists in Dallas (Smile Makeovers). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-cosmetic-dentists-dallas.png" },
  { slug:"best-veneers-dallas", title:"Best Veneers in Dallas (Top Cosmetic Dentists)", city:"Dallas", category:"Cosmetic Dentistry", metaDescription:"Best Veneers in Dallas (Top Cosmetic Dentists). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-veneers-dallas.png" },

  { slug:"top-beauty-aesthetics-dallas", title:"Top Beauty & Aesthetics Businesses in Dallas (Updated 2025)", city:"Dallas", metaDescription:"Top Beauty & Aesthetics Businesses in Dallas (Updated 2025). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/top-beauty-aesthetics-dallas.png" },
  { slug:"best-aesthetic-clinics-dallas", title:"Best Aesthetic Clinics in Dallas (All Services)", city:"Dallas", metaDescription:"Best Aesthetic Clinics in Dallas (All Services). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-aesthetic-clinics-dallas.png" },
  { slug:"best-wellness-beauty-centers-dallas", title:"Best Wellness & Beauty Centers in Dallas (Complete Care)", city:"Dallas", metaDescription:"Best Wellness & Beauty Centers in Dallas (Complete Care). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-wellness-beauty-centers-dallas.png" },
  { slug:"best-womens-beauty-services-dallas", title:"Best Women's Beauty Services in Dallas (Top Rated)", city:"Dallas", metaDescription:"Best Women's Beauty Services in Dallas (Top Rated). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-womens-beauty-services-dallas.png" },
  { slug:"best-mens-grooming-aesthetics-dallas", title:"Best Men's Grooming & Aesthetics in Dallas (Modern Treatments)", city:"Dallas", metaDescription:"Best Men's Grooming & Aesthetics in Dallas (Modern Treatments). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-mens-grooming-aesthetics-dallas.png" },

  { slug:"best-non-surgical-lifts-dallas", title:"Best Non-Surgical Facial Lifts in Dallas (2025 Edition)", city:"Dallas", metaDescription:"Best Non-Surgical Facial Lifts in Dallas (2025 Edition). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-non-surgical-lifts-dallas.png" },
  { slug:"best-anti-aging-treatments-dallas", title:"Best Anti-Aging Treatments in Dallas (Expert Approved)", city:"Dallas", metaDescription:"Best Anti-Aging Treatments in Dallas (Expert Approved). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-anti-aging-treatments-dallas.png" },
  { slug:"best-skin-tightening-dallas", title:"Best Skin Tightening Clinics in Dallas (Proven Results)", city:"Dallas", metaDescription:"Best Skin Tightening Clinics in Dallas (Proven Results). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-skin-tightening-dallas.png" },
  { slug:"best-ethnic-skincare-dallas", title:"Best Ethnic Skincare Specialists in Dallas (Inclusive Aesthetics)", city:"Dallas", metaDescription:"Best Ethnic Skincare Specialists in Dallas (Inclusive Aesthetics). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-ethnic-skincare-dallas.png" },
  { slug:"best-korean-skincare-facials-dallas", title:"Best Korean Skincare Facials in Dallas (Highly Requested)", city:"Dallas", metaDescription:"Best Korean Skincare Facials in Dallas (Highly Requested). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-korean-skincare-facials-dallas.png" },
  { slug:"best-iv-vitamin-therapy-dallas", title:"Best IV Vitamin Therapy in Dallas (Wellness Boost)", city:"Dallas", metaDescription:"Best IV Vitamin Therapy in Dallas (Wellness Boost). Discover curated providers, verified reviews, and services near you in DFW.", ogImage:"https://dallasbeautybook.com/og-images/best-iv-vitamin-therapy-dallas.png" }
];
